### ISSUE TITLE
Unknown asset error when running tests - PR attached

### ISSUE THREAD

**Issue by georgyberdyshev** [ardatan/meteor-mocha#1]
Hello @ardatan,

I have found found that there is an unknown Meteor Asset error in ardatan:mocha,
while fixing some CI issues for this Angular Meteor PR: https://github.com/Urigo/angular-meteor/pull/1927

`Error: Unknown asset: browser/phantomjs_script.js
`
**PR for the fix #2 **

You can reproduce the error by running the test in the above PR.
For example in: angular-meteor/examples/MeteorCLI/all-in-one

```
npm run test:ci

> @ test:ci angular-meteor/examples/MeteorCLI/all-in-one
> TEST_BROWSER_DRIVER=phantomjs meteor test --driver-package=ardatan:mocha --once

[[[[[ Tests ]]]]]                             

=> Started proxy.                             
...
...
=> Started MongoDB.                           
...
...
? --------------------------------
? ----- RUNNING CLIENT TESTS -----
? --------------------------------
? (STDERR) .meteor/packages/meteor-tool/.1.7.0_3.u9lhms.hf7k++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
? (STDERR) 					throw(ex);
? (STDERR) 					^
? (STDERR) 
? (STDERR) Error: Unknown asset: browser/phantomjs_script.js
? (STDERR)     at Object.absoluteFilePath (/tmp/meteor-test-runwh0j8s.p9v2s/.meteor/local/build/programs/server/boot.js:357:17)
? (STDERR)     at startPhantom (packages/ardatan:mocha/browser-tests/browser/phantomjs.js:26:29)
? (STDERR)     at startBrowser (packages/ardatan:mocha/browser-tests/server.js:26:7)
? (STDERR)     at clientTests (packages/ardatan:mocha/server.js:134:3)
? (STDERR)     at serverTests (packages/ardatan:mocha/server.js:159:7)
? (STDERR)     at mochaInstance.run.failureCount (packages/ardatan:mocha/server.js:114:13)
? (STDERR)     at done (angular-meteor/examples/MeteorCLI/all-in-one/node_modules/mocha/lib/mocha.js:608:13)
? (STDERR)     at Runner.<anonymous> (angular-meteor/examples/MeteorCLI/all-in-one/node_modules/mocha/lib/runner.js:864:5)
? (STDERR)     at emitNone (events.js:111:20)
? (STDERR)     at Runner.emit (events.js:208:7)
? (STDERR)     at angular-meteor/examples/MeteorCLI/all-in-one/node_modules/mocha/lib/runner.js:851:12
? (STDERR)     at Runner.runSuite (angular-meteor/examples/MeteorCLI/all-in-one/node_modules/mocha/lib/runner.js:635:12)
? (STDERR)     at start (angular-meteor/examples/MeteorCLI/all-in-one/node_modules/mocha/lib/runner.js:849:10)
? (STDERR)     at Runner.run (angular-meteor/examples/MeteorCLI/all-in-one/node_modules/mocha/lib/runner.js:876:5)
? (STDERR)     at Mocha.run (angular-meteor/examples/MeteorCLI/all-in-one/node_modules/mocha/lib/mocha.js:612:17)
? (STDERR)     at serverTests (packages/ardatan:mocha/server.js:112:17)
? (STDERR)     at Object.start (packages/ardatan:mocha/server.js:158:5)
? (STDERR)     at packages/meteor.js:1110:27
? (STDERR)     at Function.time (/tmp/meteor-test-runwh0j8s.p9v2s/.meteor/local/build/programs/server/profile.js:309:28)
? (STDERR)     at /tmp/meteor-test-runwh0j8s.p9v2s/.meteor/local/build/programs/server/boot.js:427:13
? (STDERR)     at /tmp/meteor-test-runwh0j8s.p9v2s/.meteor/local/build/programs/server/boot.js:472:5
? (STDERR)     at Function.run (/tmp/meteor-test-runwh0j8s.p9v2s/.meteor/local/build/programs/server/profile.js:510:12)
=> Started your app.
```

Thanks, Georgy

**Comment by georgyberdyshev** [comment]
Thanks @ardatan !
